version: "v1.0"
name: Basic GH repo test in non-default-branch
semaphore_image: "docker"
blocks:
  - build:
      jobs:
        - name: First job
          commands:
            - echo Command in non-default-branch
