version: "v3.0"
name: v2 valid pipeline
semaphore_image: "docker"
blocks:
  - name: block1
    build:
      jobs:
        - name: job1
          commands:
            - echo foo
            - echo bar
        - name: job2
          commands:
            - echo baz
  - name: block2
    build:
      jobs:
        - name: job1
          commands:
            - echo foo
            - echo bar
        - name: job2
          commands:
            - echo baz
